version: '3.8'

services:
  guidedrna:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3838:3838"
    volumes:
      - ./data:/data:rw
      - ./output:/output:rw
    environment:
      - SHINY_LOG_STDERR=1
      - R_LIBS_USER=/usr/local/lib/R/site-library
    restart: unless-stopped
    container_name: guidedrna-app
