version: '3.8'
services:
  guidedrna:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3939:3939"
    volumes:
      # Default data and output directories
      - ./data:/data:rw
      - ./output:/output:rw
      
      # Mount the entire host filesystem (Linux/Mac)
      - /:/host_system:ro
      
      # For Windows with WSL2 - mount Windows drives
      - /mnt/c:/host_drives/C:ro
      - /mnt/d:/host_drives/D:ro
      - /mnt/e:/host_drives/E:ro
      - /mnt/f:/host_drives/F:ro
      - /mnt/g:/host_drives/G:ro
      - /mnt/h:/host_drives/H:ro
      
      # Mount user home directory with write access for common use
      - ${HOME}:/host_home:rw
      
      # Mount common external drive locations
      - /media:/host_media:ro
      - /mnt:/host_mnt:ro
      
    environment:
      - SHINY_LOG_STDERR=1
      - R_LIBS_USER=/usr/local/lib/R/site-library
      # Remove user ID restrictions to avoid permission issues with mounted drives
    restart: unless-stopped
    container_name: guidedrna-app
    # Don't restrict to specific user to allow access to various mounted drives
    privileged: false
    # Add capability to access mounted filesystems
    cap_add:
      - SYS_ADMIN